
API_BASE_URL = "http://localhost:8080"

DEFAULT_TIMEOUT = 15
SHORT_TIMEOUT = 5
LONG_TIMEOUT = 30


WEBSOCKET_PORT = 8080
WEBSOCKET_RECONNECT_DELAY = 5


APP_NAME = "Sistema de Combates"
APP_VERSION = "1.0.0"